export const metadata = {
  title: 'About',
  description: 'Generated by create next app',
};

import me from '../../../public/walking-me.png';
import test from '../../../public/Headshot.kuzmin.jpg';
import Image from 'next/image';
import AboutCard from '../AboutCard';

export default function About() {
  return (
    <div>
      <div className="flex flex-col-reverse sm:flex-row align-middle  my-20 justify-center">
        <div
          id="left-side"
          className="flex flex-col items-center gap-4 justify-center "
        >
          <h2 className=" sm:text-5xl text-4xl font-bold tracking-wider ">
            Hi, I am Victoria
          </h2>

          <div className="flex flex-col items-center w-80 sm:w-96">
            <p className="flex justify-items-center sm:text-xl text-center text-lg p-5 ">
              I am currently a Software Engineer, but I have worn many hats over
              the years.
            </p>
            <p className=" md:text-lg text-base text-center w-[390px]"></p>
          </div>
        </div>

        <div
          id="right-side"
          className="flex flex-col items-center max-h-70 -mr-10"
        >
          <Image
            src={me}
            // width={300}
            alt="Cartoon of Victoria holding MacBook and coffee"
            className="sm:w-72 w-52"
            priority={true}
          />
        </div>
      </div>
      <div className="text-center text-lg">
        <button className="p-1 text-2xl focus-within:text-green-700">
          Software Engineer |
        </button>
        <button className="p-1 text-2xl focus-within:text-purple-700">
          Researcher |
        </button>
        <button className="p-1 text-2xl focus-within:text-blue-700">
          Rehab Fitness Specialist |
        </button>
        <button className="p-1 text-2xl focus-within:text-green-700">
          Sustainability Coordinator |
        </button>
        <button className="p-1 text-2xl focus-within:text-purple-700">
          Author / Illustrator
        </button>
      </div>
      <AboutCard url={test} />
    </div>
  );
}
