import './globals.css';
import Link from 'next/link';

export const metadata = {
  title: "Victoria's Portfolio",
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="h-screen flex flex-col items-stretch text-sm sm:text-base">
        <header>
          <div className="max-w-7xl mx-auto sm:px-5 px-2 flex flex-row justify-between p-3">
            <h1>
              <Link
                href="/"
                className="align-middle text-3xl text-cyan-700 font-extrabold text-transparent  bg-clip-text bg-gradient-to-r from-blue-700 to-blue-500"
                tabIndex={5}
              >
                Victoria Mertens
              </Link>
            </h1>
            <div>
              <Link className="align-middle text-lg font-bold" href="/about">
                About
              </Link>
            </div>
          </div>
        </header>
        <main id="maincontent" className="grow">
          <div className="max-w-6xl mx-auto sm:px-5 px-3 ">{children}</div>
        </main>
        <footer className="flex justify-center p-5">
          <p className="uppercase">
            &#169; {new Date().getFullYear()} - Victoria Mertens
          </p>
        </footer>
      </body>
    </html>
  );
}
