import './globals.css';

export const metadata = {
  title: "Victoria's Portfolio",
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="h-screen flex flex-col items-stretch">
        <header>
          <div className="max-w-7xl mx-auto sm:px-5 px-2 flex flex-row justify-between">
            <div>
              <h2>Victoria Mertens</h2>
            </div>
            <div>
              <a>Projects</a>
              <p className="inline px-1">|</p>
              <a>About</a>
            </div>
          </div>
        </header>
        <main className="grow">
          <div className="max-w-6xl mx-auto sm:px-5 px-3 ">{children}</div>
        </main>
        <footer>
          <p>Footer</p>
        </footer>
      </body>
    </html>
  );
}
